services:
  - type: web
    name: laravel-backend
    env: php
    plan: starter
    buildCommand: |
      # Install PHP dependencies
      composer install --no-dev --optimize-autoloader
      
      # Cache config/routes/views for performance
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      
      # Install Node.js (since PHP environment doesn't have it)
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      
      # Install frontend dependencies & build assets
      npm install
      npm run build
      
      # Run database migrations
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://your-app-url.com  # Replace with your real URL
