services:
  - type: web
    name: travel-planner-backend
    env: php
    plan: starter
    buildCommand: |
      # Ensure persistent storage directory for SQLite
      mkdir -p /var/data
      touch /var/data/database.sqlite  # Create if not exists
      
      # Install PHP dependencies
      composer install --no-dev --optimize-autoloader
      
      # Cache Laravel config, routes, views
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      
      # Install Node.js for Vite build
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      
      # Install and build frontend assets
      npm install
      npm run build
      
      # Run database migrations
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://travel-planner-1-h3oa.onrender.com # Replace with your Render URL
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
